print('       I LOVE U')
print('    ***        ***')
print('  *      *   *      *')
print(' *         *         *')
print(' *                   *')
print('  *                 *')
print('   *               *')
print('    *             *')
print('     *           *')
print('      *         *')
print('       *       *')
print('        *     *')
print('         *   *')
print('          * *')
print('           *')
